### ISSUE TITLE
display undefined in debug.go

### ISSUE THREAD

**Issue by callhands** [DaleFarnsworth-DMR/debug#1]
Get the source code:
$ go get github.com/dalefarnsworth-dmr/editcp/...

Output:
# github.com/dalefarnsworth-dmr/debug
go/src/github.com/dalefarnsworth-dmr/debug/debug.go:47:3: undefined: display
go/src/github.com/dalefarnsworth-dmr/debug/debug.go:98:2: undefined: display
go/src/github.com/dalefarnsworth-dmr/debug/debug.go:102:2: undefined: display
go/src/github.com/dalefarnsworth-dmr/debug/debug.go:106:2: undefined: display

**Comment by DaleFarnsworth** [comment]
What os are you running on?  The function display is defined on linux and windows.

**Comment by callhands** [comment]
I'm on OSX Mojave 10.14.5. I know OSX isn't explicitly supported but I thought being written in Go it would be straightforward to compile from source since it worked on Linux. There isn't really much for code plug editor support for OSX. Is there anything I could do to help with this?

**Comment by DaleFarnsworth** [comment]
Go has a mechanism, based on file name, for compiling files only on Linux, Windows, or OSX.  Currently, there are debug_linux.go and debug_windows.go files that provide the display function for those operating systems.  I am interested in having an OSX version.  However, it requires a mac, which I don't have. I'm vacationing for a week or so, and don't have access to my development machine.  When I get back, I'll say some more.

**Comment by DaleFarnsworth** [comment]
Closing because display is now defined for MacOS in debug_darwin.go.
